/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as EmailAccountsRouteImport } from './routes/email-accounts'
import { Route as ForwardersRouteImport } from './routes/forwarders'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailAccountsRoute = EmailAccountsRouteImport.update({
  id: '/email-accounts',
  path: '/email-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwardersRoute = ForwardersRouteImport.update({
  id: '/forwarders',
  path: '/forwarders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/apps': typeof AppsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/billing': typeof BillingRoute
  '/domains': typeof DomainsRoute
  '/email-accounts': typeof EmailAccountsRoute
  '/forwarders': typeof ForwardersRoute
  '/organizations': typeof OrganizationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/apps': typeof AppsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/billing': typeof BillingRoute
  '/domains': typeof DomainsRoute
  '/email-accounts': typeof EmailAccountsRoute
  '/forwarders': typeof ForwardersRoute
  '/organizations': typeof OrganizationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/apps': typeof AppsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/billing': typeof BillingRoute
  '/domains': typeof DomainsRoute
  '/email-accounts': typeof EmailAccountsRoute
  '/forwarders': typeof ForwardersRoute
  '/organizations': typeof OrganizationsRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-assistant'
    | '/apps'
    | '/audit-logs'
    | '/billing'
    | '/domains'
    | '/email-accounts'
    | '/forwarders'
    | '/organizations'
    | '/security'
    | '/settings'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-assistant'
    | '/apps'
    | '/audit-logs'
    | '/billing'
    | '/domains'
    | '/email-accounts'
    | '/forwarders'
    | '/organizations'
    | '/security'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/ai-assistant'
    | '/apps'
    | '/audit-logs'
    | '/billing'
    | '/domains'
    | '/email-accounts'
    | '/forwarders'
    | '/organizations'
    | '/security'
    | '/settings'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AppsRoute: typeof AppsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  BillingRoute: typeof BillingRoute
  DomainsRoute: typeof DomainsRoute
  EmailAccountsRoute: typeof EmailAccountsRoute
  ForwardersRoute: typeof ForwardersRoute
  OrganizationsRoute: typeof OrganizationsRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-accounts': {
      id: '/email-accounts'
      path: '/email-accounts'
      fullPath: '/email-accounts'
      preLoaderRoute: typeof EmailAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forwarders': {
      id: '/forwarders'
      path: '/forwarders'
      fullPath: '/forwarders'
      preLoaderRoute: typeof ForwardersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAssistantRoute: AiAssistantRoute,
  AppsRoute: AppsRoute,
  AuditLogsRoute: AuditLogsRoute,
  BillingRoute: BillingRoute,
  DomainsRoute: DomainsRoute,
  EmailAccountsRoute: EmailAccountsRoute,
  ForwardersRoute: ForwardersRoute,
  OrganizationsRoute: OrganizationsRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
